[package]
name = "samsynk"
version = "0.1.0"
edition = "2021"
authors = ["Sam Howson <sam@samhowson.co.uk>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.64"
tokio = { version = "1", features = ["full"] }
tokio-modbus = { version = "0.7.0", default-features = false, features = ["rtu"] }
tokio-serial = "5.4.4"
